package com.chat.mapper;

import com.chat.pojo.FriendRequest;
import com.chat.pojo.FriendRequestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FriendRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int countByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int deleteByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int insert(FriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int insertSelective(FriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    List<FriendRequest> selectByExample(FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    FriendRequest selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") FriendRequest record, @Param("example") FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") FriendRequest record, @Param("example") FriendRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FriendRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FriendRequest record);
}