package com.chat.mapper;

import com.chat.pojo.MyFriend;
import com.chat.pojo.MyFriendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MyFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int countByExample(MyFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int deleteByExample(MyFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int insert(MyFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int insertSelective(MyFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    List<MyFriend> selectByExample(MyFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    MyFriend selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") MyFriend record, @Param("example") MyFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") MyFriend record, @Param("example") MyFriendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MyFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MyFriend record);
}