package com.chat.pojo;

import java.io.Serializable;
import java.util.Date;

public class ChatMsg implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.send_user_id
     *
     * @mbggenerated
     */
    private String sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.accept_user_id
     *
     * @mbggenerated
     */
    private String acceptUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.sign_flag
     *
     * @mbggenerated
     */
    private Integer signFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column chat_msg.msg
     *
     * @mbggenerated
     */
    private String msg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_msg
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.id
     *
     * @return the value of chat_msg.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.id
     *
     * @param id the value for chat_msg.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.send_user_id
     *
     * @return the value of chat_msg.send_user_id
     *
     * @mbggenerated
     */
    public String getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.send_user_id
     *
     * @param sendUserId the value for chat_msg.send_user_id
     *
     * @mbggenerated
     */
    public void setSendUserId(String sendUserId) {
        this.sendUserId = sendUserId == null ? null : sendUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.accept_user_id
     *
     * @return the value of chat_msg.accept_user_id
     *
     * @mbggenerated
     */
    public String getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.accept_user_id
     *
     * @param acceptUserId the value for chat_msg.accept_user_id
     *
     * @mbggenerated
     */
    public void setAcceptUserId(String acceptUserId) {
        this.acceptUserId = acceptUserId == null ? null : acceptUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.createtime
     *
     * @return the value of chat_msg.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.createtime
     *
     * @param createtime the value for chat_msg.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.sign_flag
     *
     * @return the value of chat_msg.sign_flag
     *
     * @mbggenerated
     */
    public Integer getSignFlag() {
        return signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.sign_flag
     *
     * @param signFlag the value for chat_msg.sign_flag
     *
     * @mbggenerated
     */
    public void setSignFlag(Integer signFlag) {
        this.signFlag = signFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column chat_msg.msg
     *
     * @return the value of chat_msg.msg
     *
     * @mbggenerated
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column chat_msg.msg
     *
     * @param msg the value for chat_msg.msg
     *
     * @mbggenerated
     */
    public void setMsg(String msg) {
        this.msg = msg == null ? null : msg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_msg
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sendUserId=").append(sendUserId);
        sb.append(", acceptUserId=").append(acceptUserId);
        sb.append(", createtime=").append(createtime);
        sb.append(", signFlag=").append(signFlag);
        sb.append(", msg=").append(msg);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}