package com.chat.pojo;

import java.io.Serializable;
import java.util.Date;

public class FriendRequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.send_user_id
     *
     * @mbggenerated
     */
    private String sendUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.accept_user_id
     *
     * @mbggenerated
     */
    private String acceptUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend_request.createtime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.id
     *
     * @return the value of friend_request.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.id
     *
     * @param id the value for friend_request.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.send_user_id
     *
     * @return the value of friend_request.send_user_id
     *
     * @mbggenerated
     */
    public String getSendUserId() {
        return sendUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.send_user_id
     *
     * @param sendUserId the value for friend_request.send_user_id
     *
     * @mbggenerated
     */
    public void setSendUserId(String sendUserId) {
        this.sendUserId = sendUserId == null ? null : sendUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.accept_user_id
     *
     * @return the value of friend_request.accept_user_id
     *
     * @mbggenerated
     */
    public String getAcceptUserId() {
        return acceptUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.accept_user_id
     *
     * @param acceptUserId the value for friend_request.accept_user_id
     *
     * @mbggenerated
     */
    public void setAcceptUserId(String acceptUserId) {
        this.acceptUserId = acceptUserId == null ? null : acceptUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend_request.createtime
     *
     * @return the value of friend_request.createtime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend_request.createtime
     *
     * @param createtime the value for friend_request.createtime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table friend_request
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", sendUserId=").append(sendUserId);
        sb.append(", acceptUserId=").append(acceptUserId);
        sb.append(", createtime=").append(createtime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}