package com.chat.pojo;

import java.io.Serializable;

public class MyFriend implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friend.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friend.my_user_id
     *
     * @mbggenerated
     */
    private String myUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column my_friend.my_friend_id
     *
     * @mbggenerated
     */
    private String myFriendId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friend.id
     *
     * @return the value of my_friend.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friend.id
     *
     * @param id the value for my_friend.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friend.my_user_id
     *
     * @return the value of my_friend.my_user_id
     *
     * @mbggenerated
     */
    public String getMyUserId() {
        return myUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friend.my_user_id
     *
     * @param myUserId the value for my_friend.my_user_id
     *
     * @mbggenerated
     */
    public void setMyUserId(String myUserId) {
        this.myUserId = myUserId == null ? null : myUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column my_friend.my_friend_id
     *
     * @return the value of my_friend.my_friend_id
     *
     * @mbggenerated
     */
    public String getMyFriendId() {
        return myFriendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column my_friend.my_friend_id
     *
     * @param myFriendId the value for my_friend.my_friend_id
     *
     * @mbggenerated
     */
    public void setMyFriendId(String myFriendId) {
        this.myFriendId = myFriendId == null ? null : myFriendId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table my_friend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", myUserId=").append(myUserId);
        sb.append(", myFriendId=").append(myFriendId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}